In [50]:
import yfinance as yf
import pandas as pd
import scipy.stats as scipy
import numpy as np
from scipy.stats import norm

In [4]:
aapl = yf.Ticker("AAPL")
# print(aapl.options)

In [5]:
op=aapl.option_chain('2024-02-16')
print(op)

Options(calls=         contractSymbol             lastTradeDate  strike  lastPrice    bid  \
0   AAPL240216C00050000 2024-02-09 17:55:11+00:00    50.0     139.55    0.0
1   AAPL240216C00055000 2024-02-12 14:31:30+00:00    55.0     133.30    0.0
2   AAPL240216C00060000 2024-02-12 14:31:30+00:00    60.0     128.30    0.0
3   AAPL240216C00065000 2024-01-04 20:52:32+00:00    65.0     117.06  120.5
4   AAPL240216C00070000 2024-02-02 16:12:50+00:00    70.0     116.53    0.0
..                  ...                       ...     ...        ...    ...
64  AAPL240216C00300000 2024-02-12 14:59:11+00:00   300.0       0.01    0.0
65  AAPL240216C00305000 2024-02-06 18:38:46+00:00   305.0       0.01    0.0
66  AAPL240216C00310000 2024-02-12 14:30:00+00:00   310.0       0.01    0.0
67  AAPL240216C00315000 2023-09-15 17:36:06+00:00   315.0       0.03    0.0
68  AAPL240216C00320000 2024-02-12 20:25:17+00:00   320.0       0.01    0.0

       ask  change  percentChange  volume  openInterest  impliedVolatility  \
0     0.00     0.0            0.0       2             0           0.000010
1     0.00     0.0            0.0       2             0           0.000010
2     0.00     0.0            0.0       2             0           0.000010
3   121.35     0.0            0.0       1             1           0.000010
4     0.00     0.0            0.0       5             0           0.000010
..     ...     ...            ...     ...           ...                ...
64    0.00     0.0            0.0     300             0           0.500005
65    0.00     0.0            0.0       3             0           0.500005
66    0.00     0.0            0.0       2             0           0.500005
67    0.03     0.0            0.0      23           285           1.656252
68    0.00     0.0            0.0      14             0           0.500005

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
..         ...          ...      ...
64       False      REGULAR      USD
65       False      REGULAR      USD
66       False      REGULAR      USD
67       False      REGULAR      USD
68       False      REGULAR      USD

[69 rows x 14 columns], puts=         contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0   AAPL240216P00050000 2024-01-08 17:55:42+00:00    50.0       0.01    0.00
1   AAPL240216P00055000 2024-02-12 19:15:38+00:00    55.0       0.01    0.00
2   AAPL240216P00060000 2023-11-21 19:50:14+00:00    60.0       0.01    0.00
3   AAPL240216P00065000 2023-11-24 16:40:32+00:00    65.0       0.01    0.00
4   AAPL240216P00070000 2024-01-04 16:20:13+00:00    70.0       0.01    0.00
5   AAPL240216P00075000 2024-01-31 14:46:48+00:00    75.0       0.01    0.00
6   AAPL240216P00080000 2024-01-22 14:40:42+00:00    80.0       0.01    0.00
7   AAPL240216P00085000 2024-01-22 15:05:56+00:00    85.0       0.01    0.00
8   AAPL240216P00090000 2024-01-22 14:53:21+00:00    90.0       0.01    0.00
9   AAPL240216P00095000 2024-02-06 17:43:05+00:00    95.0       0.01    0.00
10  AAPL240216P00100000 2024-02-05 14:30:02+00:00   100.0       0.01    0.00
11  AAPL240216P00105000 2024-02-12 14:30:01+00:00   105.0       0.01    0.00
12  AAPL240216P00110000 2024-02-09 20:32:47+00:00   110.0       0.01    0.00
13  AAPL240216P00115000 2024-02-09 20:32:47+00:00   115.0       0.01    0.00
14  AAPL240216P00120000 2024-02-09 20:32:55+00:00   120.0       0.01    0.00
15  AAPL240216P00125000 2024-02-09 20:41:30+00:00   125.0       0.01    0.00
16  AAPL240216P00130000 2024-02-12 16:32:09+00:00   130.0       0.01    0.00
17  AAPL240216P00135000 2024-02-12 17:03:13+00:00   135.0       0.01    0.00
18  AAPL240216P00140000 2024-02-09 20:55:46+00:00   140.0       0.01    0.00
19  AAPL240216P00145000 2024-02-12 14:56:51+00:00   145.0       0.01    0.00
20  AAPL240216P00150000 2024-02-12 19:58:51+00:00   150.0       0.01    0.00
21  AAPL240216P00155000 2024-02-12 20:49:51+00:00   155.0       0.01    0.00
22  AAPL240216P00157500 2024-02-12 19:16:59+00:00   157.5       0.01    0.00
23  AAPL240216P00160000 2024-02-12 20:56:36+00:00   160.0       0.02    0.00
24  AAPL240216P00162500 2024-02-12 19:18:04+00:00   162.5       0.02    0.00
25  AAPL240216P00165000 2024-02-12 20:54:42+00:00   165.0       0.02    0.00
26  AAPL240216P00167500 2024-02-12 19:39:39+00:00   167.5       0.03    0.00
27  AAPL240216P00170000 2024-02-12 20:58:52+00:00   170.0       0.04    0.00
28  AAPL240216P00172500 2024-02-12 20:59:06+00:00   172.5       0.05    0.00
29  AAPL240216P00175000 2024-02-12 20:59:40+00:00   175.0       0.06    0.00
30  AAPL240216P00177500 2024-02-12 20:59:56+00:00   177.5       0.09    0.00
31  AAPL240216P00180000 2024-02-12 20:59:56+00:00   180.0       0.15    0.00
32  AAPL240216P00182500 2024-02-12 20:59:57+00:00   182.5       0.33    0.00
33  AAPL240216P00185000 2024-02-12 20:59:58+00:00   185.0       0.79    0.00
34  AAPL240216P00187500 2024-02-12 20:59:57+00:00   187.5       1.77    0.00
35  AAPL240216P00190000 2024-02-12 20:55:55+00:00   190.0       3.50    0.00
36  AAPL240216P00192500 2024-02-12 20:59:37+00:00   192.5       5.55    0.00
37  AAPL240216P00195000 2024-02-12 20:59:17+00:00   195.0       8.02    0.00
38  AAPL240216P00197500 2024-02-12 20:18:02+00:00   197.5      10.40    0.00
39  AAPL240216P00200000 2024-02-12 20:54:40+00:00   200.0      12.70    0.00
40  AAPL240216P00202500 2024-02-12 20:49:51+00:00   202.5      15.30    0.00
41  AAPL240216P00205000 2024-02-12 20:49:51+00:00   205.0      17.80    0.00
42  AAPL240216P00207500 2024-02-09 20:36:23+00:00   207.5      18.70    0.00
43  AAPL240216P00210000 2024-02-12 19:59:45+00:00   210.0      23.10    0.00
44  AAPL240216P00212500 2024-02-01 16:13:07+00:00   212.5      26.79    0.00
45  AAPL240216P00215000 2024-02-09 14:56:12+00:00   215.0      26.45    0.00
46  AAPL240216P00217500 2024-02-09 19:28:12+00:00   217.5      28.65    0.00
47  AAPL240216P00220000 2024-02-07 15:32:07+00:00   220.0      30.25    0.00
48  AAPL240216P00225000 2024-02-09 16:54:19+00:00   225.0      35.24    0.00
49  AAPL240216P00230000 2024-02-06 20:56:34+00:00   230.0      41.02    0.00
50  AAPL240216P00235000 2023-11-16 16:00:49+00:00   235.0      45.45   37.10
51  AAPL240216P00240000 2023-12-26 16:20:14+00:00   240.0      47.02   46.95
52  AAPL240216P00260000 2023-12-19 20:04:49+00:00   260.0      63.75   67.70
53  AAPL240216P00265000 2023-12-22 14:38:46+00:00   265.0      70.50   68.55
54  AAPL240216P00270000 2023-12-21 17:05:25+00:00   270.0      75.74   77.90
55  AAPL240216P00300000 2024-02-02 14:38:00+00:00   300.0     117.50    0.00
56  AAPL240216P00315000 2023-12-21 16:48:12+00:00   315.0     120.10  122.85
57  AAPL240216P00320000 2023-12-29 19:48:23+00:00   320.0     127.60  127.65

       ask  change  percentChange   volume  openInterest  impliedVolatility  \
0     0.01     0.0            0.0     28.0         251.0           3.875000
1     0.00     0.0            0.0     36.0           0.0           0.500005
2     0.03     0.0            0.0      1.0          88.0           3.625001
3     0.03     0.0            0.0     40.0         353.0           3.375002
4     0.08     0.0            0.0      5.0         580.0           3.453126
5     0.00     0.0            0.0      1.0           0.0           0.500005
6     0.00     0.0            0.0    108.0           0.0           1.000005
7     0.00     0.0            0.0    110.0           0.0           0.500005
8     0.00     0.0            0.0    284.0           0.0           0.500005
9     0.00     0.0            0.0      3.0           0.0           0.500005
10    0.00     0.0            0.0      1.0           0.0           0.500005
11    0.00     0.0            0.0      1.0           0.0           0.500005
12    0.00     0.0            0.0   1944.0           0.0           0.500005
13    0.00     0.0            0.0     86.0           0.0           0.500005
14    0.00     0.0            0.0    184.0           0.0           0.500005
15    0.00     0.0            0.0    790.0           0.0           0.500005
16    0.00     0.0            0.0      1.0           0.0           0.500005
17    0.00     0.0            0.0      1.0           0.0           0.500005
18    0.00     0.0            0.0    203.0           0.0           0.500005
19    0.00     0.0            0.0     10.0           0.0           0.500005
20    0.00     0.0            0.0     39.0           0.0           0.500005
21    0.00     0.0            0.0    448.0           0.0           0.500005
22    0.00     0.0            0.0    327.0           0.0           0.250007
23    0.00     0.0            0.0    135.0           0.0           0.250007
24    0.00     0.0            0.0     18.0           0.0           0.250007
25    0.00     0.0            0.0    405.0           0.0           0.250007
26    0.00     0.0            0.0    226.0           0.0           0.250007
27    0.00     0.0            0.0   1335.0           0.0           0.250007
28    0.00     0.0            0.0   1050.0           0.0           0.125009
29    0.00     0.0            0.0   3333.0           0.0           0.125009
30    0.00     0.0            0.0   1850.0           0.0           0.125009
31    0.00     0.0            0.0   9255.0           0.0           0.125009
32    0.00     0.0            0.0   7980.0           0.0           0.062509
33    0.00     0.0            0.0  25788.0           0.0           0.031260
34    0.00     0.0            0.0  20904.0           0.0           0.000010
35    0.00     0.0            0.0   9938.0           0.0           0.000010
36    0.00     0.0            0.0    724.0           0.0           0.000010
37    0.00     0.0            0.0    513.0           0.0           0.000010
38    0.00     0.0            0.0     21.0           0.0           0.000010
39    0.00     0.0            0.0   2799.0           0.0           0.000010
40    0.00     0.0            0.0   1774.0           0.0           0.000010
41    0.00     0.0            0.0    859.0           0.0           0.000010
42    0.00     0.0            0.0      8.0           0.0           0.000010
43    0.00     0.0            0.0    749.0           0.0           0.000010
44    0.00     0.0            0.0      4.0           0.0           0.000010
45    0.00     0.0            0.0      2.0           0.0           0.000010
46    0.00     0.0            0.0      NaN           NaN           0.000010
47    0.00     0.0            0.0      1.0           0.0           0.000010
48    0.00     0.0            0.0     10.0           0.0           0.000010
49    0.00     0.0            0.0      1.0           0.0           0.000010
50   38.60     0.0            0.0     36.0           0.0           0.000010
51   48.15     0.0            0.0      2.0           0.0           0.000010
52   68.95     0.0            0.0      NaN           0.0           0.000010
53   69.30     0.0            0.0      1.0           0.0           0.000010
54   78.95     0.0            0.0      NaN           0.0           0.000010
55    0.00     0.0            0.0      2.0           0.0           0.000010
56  123.95     0.0            0.0      NaN           0.0           0.000010
57  128.50     0.0            0.0      2.0           0.0           0.000010

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
5        False      REGULAR      USD
6        False      REGULAR      USD
7        False      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26       False      REGULAR      USD
27       False      REGULAR      USD
28       False      REGULAR      USD
29       False      REGULAR      USD
30       False      REGULAR      USD
31       False      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34        True      REGULAR      USD
35        True      REGULAR      USD
36        True      REGULAR      USD
37        True      REGULAR      USD
38        True      REGULAR      USD
39        True      REGULAR      USD
40        True      REGULAR      USD
41        True      REGULAR      USD
42        True      REGULAR      USD
43        True      REGULAR      USD
44        True      REGULAR      USD
45        True      REGULAR      USD
46        True      REGULAR      USD
47        True      REGULAR      USD
48        True      REGULAR      USD
49        True      REGULAR      USD
50        True      REGULAR      USD
51        True      REGULAR      USD
52        True      REGULAR      USD
53        True      REGULAR      USD
54        True      REGULAR      USD
55        True      REGULAR      USD
56        True      REGULAR      USD
57        True      REGULAR      USD  , underlying={'language': 'en-US', 'region': 'US', 'quoteType': 'EQUITY', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'currency': 'USD', 'marketState': 'PRE', 'regularMarketChangePercent': -0.9001917, 'regularMarketPrice': 187.15, 'exchange': 'NMS', 'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EST', 'gmtOffSetMilliseconds': -18000000, 'market': 'us_market', 'esgPopulated': False, 'firstTradeDateMilliseconds': 345479400000, 'priceHint': 2, 'preMarketChange': -1.0399933, 'preMarketChangePercent': -0.5557004, 'preMarketTime': 1707818030, 'preMarketPrice': 186.11, 'regularMarketChange': -1.7000122, 'regularMarketTime': 1707771601, 'regularMarketDayHigh': 188.6699, 'regularMarketDayRange': '186.79 - 188.6699', 'regularMarketDayLow': 186.79, 'regularMarketVolume': 40912269, 'regularMarketPreviousClose': 188.85, 'bid': 0.0, 'ask': 0.0, 'bidSize': 12, 'askSize': 9, 'fullExchangeName': 'NasdaqGS', 'financialCurrency': 'USD', 'regularMarketOpen': 188.415, 'averageDailyVolume3Month': 53280544, 'averageDailyVolume10Day': 57312960, 'fiftyTwoWeekLowChange': 43.25, 'fiftyTwoWeekLowChangePercent': 0.30055594, 'fiftyTwoWeekRange': '143.9 - 199.62', 'fiftyTwoWeekHighChange': -12.470001, 'fiftyTwoWeekHighChangePercent': -0.062468696, 'fiftyTwoWeekLow': 143.9, 'fiftyTwoWeekHigh': 199.62, 'fiftyTwoWeekChangePercent': 22.160578, 'dividendDate': 1707955200, 'earningsTimestamp': 1706824800, 'earningsTimestampStart': 1714647540, 'earningsTimestampEnd': 1714996800, 'trailingAnnualDividendRate': 0.95, 'trailingPE': 29.151089, 'dividendRate': 0.96, 'trailingAnnualDividendYield': 0.005030447, 'dividendYield': 0.51, 'epsTrailingTwelveMonths': 6.42, 'epsForward': 7.16, 'epsCurrentYear': 6.57, 'priceEpsCurrentYear': 28.485538, 'sharesOutstanding': 15441899520, 'bookValue': 4.793, 'fiftyDayAverage': 190.435, 'fiftyDayAverageChange': -3.2850037, 'fiftyDayAverageChangePercent': -0.01725, 'twoHundredDayAverage': 183.18465, 'twoHundredDayAverageChange': 3.9653473, 'twoHundredDayAverageChangePercent': 0.021646723, 'marketCap': 2889951477760, 'forwardPE': 26.138268, 'priceToBook': 39.046524, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '2.1 - Buy', 'tradeable': False, 'cryptoTradeable': False, 'displayName': 'Apple', 'symbol': 'AAPL'})

In [6]:
del op.calls['currency']

In [7]:
op.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize
0,AAPL240216C00050000,2024-02-09 17:55:11+00:00,50.0,139.55,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR
1,AAPL240216C00055000,2024-02-12 14:31:30+00:00,55.0,133.30,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR
2,AAPL240216C00060000,2024-02-12 14:31:30+00:00,60.0,128.30,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR
3,AAPL240216C00065000,2024-01-04 20:52:32+00:00,65.0,117.06,120.5,121.35,0.0,0.0,1,1,0.000010,True,REGULAR
4,AAPL240216C00070000,2024-02-02 16:12:50+00:00,70.0,116.53,0.0,0.00,0.0,0.0,5,0,0.000010,True,REGULAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,AAPL240216C00300000,2024-02-12 14:59:11+00:00,300.0,0.01,0.0,0.00,0.0,0.0,300,0,0.500005,False,REGULAR
65,AAPL240216C00305000,2024-02-06 18:38:46+00:00,305.0,0.01,0.0,0.00,0.0,0.0,3,0,0.500005,False,REGULAR
66,AAPL240216C00310000,2024-02-12 14:30:00+00:00,310.0,0.01,0.0,0.00,0.0,0.0,2,0,0.500005,False,REGULAR
67,AAPL240216C00315000,2023-09-15 17:36:06+00:00,315.0,0.03,0.0,0.03,0.0,0.0,23,285,1.656252,False,REGULAR
68,AAPL240216C00320000,2024-02-12 20:25:17+00:00,320.0,0.01,0.0,0.00,0.0,0.0,14,0,0.500005,False,REGULAR

In [8]:
hist=aapl.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.099192,0.099623,0.099192,0.099192,469033600,0.00,0.0
1980-12-15 00:00:00-05:00,0.094448,0.094448,0.094017,0.094017,175884800,0.00,0.0
1980-12-16 00:00:00-05:00,0.087548,0.087548,0.087117,0.087117,105728000,0.00,0.0
1980-12-17 00:00:00-05:00,0.089273,0.089704,0.089273,0.089273,86441600,0.00,0.0
1980-12-18 00:00:00-05:00,0.091861,0.092292,0.091861,0.091861,73449600,0.00,0.0
...,...,...,...,...,...,...,...
2024-02-06 00:00:00-05:00,186.621869,189.068743,186.531987,189.058762,43490800,0.00,0.0
2024-02-07 00:00:00-05:00,190.397053,190.806534,188.369641,189.168625,53439000,0.00,0.0
2024-02-08 00:00:00-05:00,189.148646,189.298448,187.111252,188.080017,40962000,0.00,0.0
2024-02-09 00:00:00-05:00,188.649994,189.990005,188.000000,188.850006,45099900,0.24,0.0
2024-02-12 00:00:00-05:00,188.419998,188.669998,186.789993,187.149994,41738500,0.00,0.0

In [51]:
hist['returns']=(hist['Close']/hist['Open']-1)*100

In [10]:
hist.reset_index()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,returns
0,1980-12-12 00:00:00-05:00,0.099192,0.099623,0.099192,0.099192,469033600,0.00,0.0,0.000000
1,1980-12-15 00:00:00-05:00,0.094448,0.094448,0.094017,0.094017,175884800,0.00,0.0,-0.456594
2,1980-12-16 00:00:00-05:00,0.087548,0.087548,0.087117,0.087117,105728000,0.00,0.0,-0.492577
3,1980-12-17 00:00:00-05:00,0.089273,0.089704,0.089273,0.089273,86441600,0.00,0.0,0.000000
4,1980-12-18 00:00:00-05:00,0.091861,0.092292,0.091861,0.091861,73449600,0.00,0.0,0.000000
...,...,...,...,...,...,...,...,...,...
10877,2024-02-06 00:00:00-05:00,186.621869,189.068743,186.531987,189.058762,43490800,0.00,0.0,1.305792
10878,2024-02-07 00:00:00-05:00,190.397053,190.806534,188.369641,189.168625,53439000,0.00,0.0,-0.645193
10879,2024-02-08 00:00:00-05:00,189.148646,189.298448,187.111252,188.080017,40962000,0.00,0.0,-0.564968
10880,2024-02-09 00:00:00-05:00,188.649994,189.990005,188.000000,188.850006,45099900,0.24,0.0,0.106023
10881,2024-02-12 00:00:00-05:00,188.419998,188.669998,186.789993,187.149994,41738500,0.00,0.0,-0.674028

In [11]:
hist=hist.drop(hist.index[0],axis=0)

In [22]:
std=hist['returns'].std()
print(std)

2.2912042493008786

In [27]:
vol=std/np.sqrt(10881)

0.021964908625337773

# BSCs

In [35]:
r=0.01
def Black_Scholes(K,dte,S_t,Type='C'):
    d_1=(np.log(S_t/K)+(r+(vol**2)/2)*(dte/365))/(vol*np.sqrt(dte/365))
    d_2=d_1-(vol*np.sqrt(dte/365))
    try:
        if Type=='C':
            Price=S_t*norm.cdf(x=d_1,loc=0,scale=1)-K*np.exp(-r*(dte)/2)*norm.cdf(x=d_2,loc=0,scale=1)
        elif Type=='P':
            Price=K*np.exp(-r*(dte/365))*norm.cdf(x=-d_2,loc=0,scale=1)-S_t*norm.cdf(x=-d_1,loc=0,scale=1)
        return Price
    except:
        print("Error")

In [49]:
op.calls['dte']=3
op.calls

NameError: name 'norm' is not defined

In [52]:
op.calls['BSC']=Black_Scholes(op.calls['strike'],3,187,Type='C')
op.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,dte,BSC
0,AAPL240216C00050000,2024-02-09 17:55:11+00:00,50.0,139.55,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR,3,137.744403
1,AAPL240216C00055000,2024-02-12 14:31:30+00:00,55.0,133.30,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR,3,132.818843
2,AAPL240216C00060000,2024-02-12 14:31:30+00:00,60.0,128.30,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR,3,127.893284
3,AAPL240216C00065000,2024-01-04 20:52:32+00:00,65.0,117.06,120.5,121.35,0.0,0.0,1,1,0.000010,True,REGULAR,3,122.967724
4,AAPL240216C00070000,2024-02-02 16:12:50+00:00,70.0,116.53,0.0,0.00,0.0,0.0,5,0,0.000010,True,REGULAR,3,118.042164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,AAPL240216C00300000,2024-02-12 14:59:11+00:00,300.0,0.01,0.0,0.00,0.0,0.0,300,0,0.500005,False,REGULAR,3,0.000000
65,AAPL240216C00305000,2024-02-06 18:38:46+00:00,305.0,0.01,0.0,0.00,0.0,0.0,3,0,0.500005,False,REGULAR,3,0.000000
66,AAPL240216C00310000,2024-02-12 14:30:00+00:00,310.0,0.01,0.0,0.00,0.0,0.0,2,0,0.500005,False,REGULAR,3,0.000000
67,AAPL240216C00315000,2023-09-15 17:36:06+00:00,315.0,0.03,0.0,0.03,0.0,0.0,23,285,1.656252,False,REGULAR,3,0.000000
68,AAPL240216C00320000,2024-02-12 20:25:17+00:00,320.0,0.01,0.0,0.00,0.0,0.0,14,0,0.500005,False,REGULAR,3,0.000000

In [68]:
diff = pd.DataFrame()
op.calls.shape

(69, 15)

In [77]:
diff['lastPrice']=extracted_col
extracted_col=op.calls['lastPrice']
diff['BSC']=op.calls['BSC']
diff['diff']=diff['BSC']-diff['lastPrice']
diff

    lastPrice         BSC      diff
0      139.55  137.744403 -1.805597
1      133.30  132.818843 -0.481157
2      128.30  127.893284 -0.406716
3      117.06  122.967724  5.907724
4      116.53  118.042164  1.512164
..        ...         ...       ...
64       0.01    0.000000 -0.010000
65       0.01    0.000000 -0.010000
66       0.01    0.000000 -0.010000
67       0.03    0.000000 -0.030000
68       0.01    0.000000 -0.010000

[69 rows x 3 columns]